/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package client;

import javax.swing.JTextArea;

/**
 *
 * @author franc
 */
public class Ventas extends javax.swing.JDialog {

    /**
     * Creates new form Ventas
     */
    public Ventas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tAreaProductos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        btnComprar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfResultado = new javax.swing.JTextArea();
        lSaldo = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        lVentas1 = new javax.swing.JLabel();
        ISaldo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tAreaProductos.setText(getProducts());
        tAreaProductos.setEditable(false);
        tAreaProductos.setColumns(20);
        tAreaProductos.setLineWrap(true);
        tAreaProductos.setRows(5);
        jScrollPane1.setViewportView(tAreaProductos);
        tAreaProductos.getAccessibleContext().setAccessibleName("txtAreaProductos");

        jLabel1.setText("Productos");

        tfCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCantidadActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingresa codigo");

        jLabel3.setText("Ingresa Cantidad");

        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        tfResultado.setEditable(false);
        tfResultado.setColumns(20);
        tfResultado.setLineWrap(true);
        tfResultado.setRows(5);
        jScrollPane2.setViewportView(tfResultado);

        lSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lSaldo.setText("Saldo");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lVentas1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lVentas1.setText("Ventas");

        ISaldo.setText("" + getSaldo(1));
        ISaldo.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lVentas1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                .addComponent(tfCodigo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfCantidad)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ISaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lSaldo)
                            .addComponent(lVentas1))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ISaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(btnComprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        tfCantidad.getAccessibleContext().setAccessibleName("lblCantidad");
        tfCodigo.getAccessibleContext().setAccessibleName("lblCodigo");
        btnComprar.getAccessibleContext().setAccessibleName("btnComprar");
        btnComprar.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCantidadActionPerformed

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        String cantidad = tfCantidad.getText();
        String codigo = tfCodigo.getText();

        if (cantidad.isEmpty() || codigo.isEmpty()) {
            tfResultado.setText("Los campos no pueden estar vacíos");
            return;
        }

        try {
            double saldo = Double.parseDouble(ISaldo.getText());
            int cant = Integer.parseInt(cantidad);
            int cod = Integer.parseInt(codigo);
            String ans = sellProduct(cod, cant, saldo);
            tfResultado.setText(ans);
            tAreaProductos.setText(getProducts());

            double newSaldo = saldo;
            if (saldo - cant * Double.parseDouble(getPrecio(cod)) >= 0) {
                newSaldo = saldo - cant * Double.parseDouble(getPrecio(cod));
            }
            updateSaldo(1, newSaldo);
            ISaldo.setText(newSaldo + "");

        } catch (NumberFormatException e) {

            tfResultado.setText("Los campos deben contener números válidos");
        }

    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String codigo = tfCodigo.getText();
        if (codigo.isEmpty()) {
            tfResultado.setText("Ingrese el codigo para realizar la busqueda");
        }
        try {
            int cod = Integer.parseInt(codigo);
            String ans = getProduct(cod);
            tAreaProductos.setText(ans);
        } catch (NumberFormatException e) {
            tfResultado.setText("El campo de codigo debe contener números validos");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventas dialog = new Ventas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ISaldo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lSaldo;
    private javax.swing.JLabel lVentas1;
    private javax.swing.JTextArea tAreaProductos;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextArea tfResultado;
    // End of variables declaration//GEN-END:variables

    private static String getProducts() {
        ws.ProductoController_Service service = new ws.ProductoController_Service();
        ws.ProductoController port = service.getProductoControllerPort();
        return port.getProducts();
    }

    private static String sellProduct(int code, int cantidad, double saldo) {
        ws.ProductoController_Service service = new ws.ProductoController_Service();
        ws.ProductoController port = service.getProductoControllerPort();
        return port.sellProduct(code, cantidad, saldo);
    }

    private static String getProduct(int code) {
        ws.ProductoController_Service service = new ws.ProductoController_Service();
        ws.ProductoController port = service.getProductoControllerPort();
        return port.getProduct(code);
    }

    private static String getPersona(int code) {
        ws.usuario.PersonaController_Service service = new ws.usuario.PersonaController_Service();
        ws.usuario.PersonaController port = service.getPersonaControllerPort();
        return port.getPersona(code);
    }

    private static double getSaldo(int code) {
        ws.usuario.PersonaController_Service service = new ws.usuario.PersonaController_Service();
        ws.usuario.PersonaController port = service.getPersonaControllerPort();
        return port.getSaldo(code);
    }

    private static String updateSaldo(int code, double nuevoSaldo) {
        ws.usuario.PersonaController_Service service = new ws.usuario.PersonaController_Service();
        ws.usuario.PersonaController port = service.getPersonaControllerPort();
        return port.updateSaldo(code, nuevoSaldo);
    }

    private static String getPrecio(int code) {
        ws.ProductoController_Service service = new ws.ProductoController_Service();
        ws.ProductoController port = service.getProductoControllerPort();
        return port.getPrecio(code);
    }

}
