package conexion;

import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class PruebaConectar extends javax.swing.JPanel {

    /**
     * Creates new form PruebaConectar
     */
    public PruebaConectar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();

        btnAceptar.setText("Conectarse");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(btnAceptar)
                                .addContainerGap(162, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(btnAceptar)
                                .addContainerGap(164, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAceptarActionPerformed
        Conectar conecta = new Conectar();
        Connection con = conecta.getConexion();
        if (con != null) {
            JOptionPane.showMessageDialog(this, "Conexión establecida con éxito");
        } else {
            JOptionPane.showMessageDialog(this, "Error al establecer la conexión");
        }
    }// GEN-LAST:event_btnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;

    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        JFrame frame = new JFrame("Prueba Conectar");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new PruebaConectar());
        frame.pack();
        frame.setLocationRelativeTo(null); // Centrar la ventana
        frame.setVisible(true);
    }
}
